name: Deploy Hexo to Main Branch

on:
  push:
    branches: [ hexo ] # 当向 hexo 分支推送代码时触发这个 Action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 建议设置一个环境（可选，但更规范）
    # environment: production

    steps:
      # 步骤1：检出 hexo 分支的源代码
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          ref: hexo # 检出触发本次运行的 hexo 分支代码
          # 获取足够的历史记录，这对于某些 Hexo 主题或插件可能是必要的
          fetch-depth: 0 # '0' 表示获取所有历史记录。若为加快速度，可设置为一个较大的数，如 '50'

      # 步骤2：设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # 使用你需要的 Node.js 版本，18或20都是常见选择
          cache: 'npm' # 添加 npm 缓存，通常比只使用 actions/cache 更简单

      # 步骤3：缓存 npm 依赖以加速后续构建 (可选，setup-node 的 cache 可能已足够)
      # - name: Setup Cache
      #   uses: actions/cache@v4
      #   id: cache
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-node-

      # 步骤4：安装依赖
      - name: Install Dependencies
        run: npm ci

      # 步骤5：生成静态网站文件
      - name: Generate Static Files
        run: |
          npm run build # 或者直接运行 hexo generate
          # 如果你的 package.json 的 scripts 里没有 build，就用 `npx hexo generate`

      # 步骤6：部署到 main 分支
      - name: Deploy to Main
        uses: peaceiris/actions-gh-pages@v3
        with:
          # 使用之前设置的 Secret
          deploy_key: ${{ secrets.HEXO_DEPLOY_PAT }}
          # 或者使用 Personal Access Token
          # personal_access_token: ${{ secrets.HEXO_DEPLOY_PAT }}
          # 设置发布到的分支
          publish_branch: main
          # 设置包含静态文件的目录
          publish_dir: ./public
          # 可选：配置提交信息
          commit_message: ${{ github.event.head_commit.message }} - Automated Deployment from Hexo Branch
          # 强制推送，覆盖main分支的历史（对于部署分支这是正常的）
          # 移除 force_orphan 参数，使用 action 的默认行为或考虑 --force-with-lease
          # force_orphan: true
          # 设置 Git 用户信息 (保持默认的机器用户即可)
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
